/**
 * Rule contract — `<a name>` / `<a id>` → `::anchor{#id}`.
 *
 * The prose contract lives in `anchors.ts`; this is the executable half of it.
 * Every claim that file makes about evidence, false friends and mutation
 * robustness has a test here, and the placement rules have end-to-end tests
 * through the real pipeline rather than through the registry alone — because
 * placement is the part that interacts with fifteen other passes and the part
 * that broke twice while it was being written.
 */
import { describe, expect, it } from "vitest";
import { convert } from "./pipeline.js";
import { AnchorRegistry, harvestAnchors } from "./anchors.js";
import { parseHtml } from "../ladom/parse.js";
import { type LadomNode, walkElements } from "../ladom/types.js";
import { resolveProfile } from "../biomd-ast/index.js";

const SPEC = resolveProfile("spec-1.6");

async function md(html: string): Promise<string> {
  const result = await convert(Buffer.from(html, "utf8"), { profile: SPEC, sourceName: "probe.htm" });
  return result.markdown;
}

async function convertProbe(html: string) {
  return convert(Buffer.from(html, "utf8"), { profile: SPEC, sourceName: "probe.htm" });
}

/** Identifiers harvested from a fragment, in source order. */
function harvest(html: string): string[] {
  return harvestAnchors(parseHtml(html).root).anchors.map((a) => a.identifier);
}

function page(body: string): string {
  return `<html><body>${body}</body></html>`;
}

/** The `::anchor` lines of a document, in order. */
function anchors(markdown: string): string[] {
  return markdown.split("\n").filter((line) => line.startsWith("::anchor"));
}

// ---------------------------------------------------------------------------
// Invariant: the attribute is the whole evidence
// ---------------------------------------------------------------------------

describe("what declares a destination", () => {
  it("reads `name` and `id` on an anchor element", () => {
    expect(harvest(page(`<p><a name="one">x</a></p><p><a id="two">y</a></p>`))).toEqual(["one", "two"]);
  });

  it("emits both when one element carries two different values", () => {
    // HTML 4 requires them to be equal; when a page disagrees with itself both
    // are live destinations in a browser, and dropping either breaks whichever
    // link used it. `id` first, so the order is a property of the rule and not
    // of the attribute order the editor happened to write.
    expect(harvest(page(`<p><a name="n" id="i">x</a></p>`))).toEqual(["i", "n"]);
  });

  it("is blind to everything except the attribute", () => {
    const a = harvest(page(`<p class="t8"><a name="k" class="menu" title="Дискография">x</a></p>`));
    const b = harvest(page(`<div id="wrapper"><span><a name="k">x</a></span></div>`));
    expect(a).toEqual(["k"]);
    expect(b).toEqual(["k"]);
  });

  it("keeps a Cyrillic identifier byte for byte", () => {
    // A fragment is matched literally against the `#…` that reaches it, so
    // transliterating here would break the pairing rather than improve it.
    expect(harvest(page(`<p><a name="раздел">x</a></p>`))).toEqual(["раздел"]);
  });
});

// ---------------------------------------------------------------------------
// False friends, each tested for non-firing
// ---------------------------------------------------------------------------

describe("false friends", () => {
  it("a fragment link is a reference, not a declaration", async () => {
    const html = page(`<p><a href="#gone">to the notes</a></p>`);
    expect(harvest(html)).toEqual([]);
    expect(anchors(await md(html))).toEqual([]);
  });

  it("an id on anything that is not an anchor element is not a destination", async () => {
    // `xtra_shelechov.htm` carries exactly one of these — `<table id="table1">`,
    // generated by FrontPage and mentioned by no link on the page.
    const html = page(`<table id="table1"><tr><td>cell</td></tr></table><div id="layer2">x</div>`);
    expect(harvest(html)).toEqual([]);
    expect(anchors(await md(html))).toEqual([]);
  });

  it("an empty or whitespace-only value declares nothing", () => {
    expect(harvest(page(`<p><a name="">x</a><a id="   ">y</a></p>`))).toEqual([]);
  });

  it("a value the shorthand cannot carry is refused rather than repaired", () => {
    const result = harvestAnchors(parseHtml(page(`<p><a name="two words">x</a></p>`)).root);
    expect(result.anchors).toEqual([]);
    expect(result.rejected).toHaveLength(1);
    expect(result.rejected[0]?.reason).toMatch(/cannot be written/u);
  });
});

// ---------------------------------------------------------------------------
// A destination and a link at once
// ---------------------------------------------------------------------------

describe("an element that is both", () => {
  it("keeps the marker and the link", async () => {
    // The shape `barrios` and `new_dyens` use for a footnote marker.
    const out = await md(page(`<p>БАРРИОС<sup><a name="2" href="#1">1</a></sup> — гитарист.</p>`));
    expect(anchors(out)).toEqual(["::anchor{#2}"]);
    expect(out).toContain("[1](#1)");
  });

  it("does not record the element as a removal once it became a marker", async () => {
    const result = await convertProbe(page(`<p><a name="k">Название альбома</a></p>`));
    const removals = result.ledger.filter((e) => e.terminal.kind === "REMOVED");
    expect(removals.some((e) => e.terminal.kind === "REMOVED" && /no navigable destination/u.test(e.terminal.reason))).toBe(false);
    expect(result.markdown).toContain("Название альбома");
  });
});

// ---------------------------------------------------------------------------
// Duplicates
// ---------------------------------------------------------------------------

describe("a duplicate identifier", () => {
  it("keeps the first declaration and records the rest", () => {
    const result = harvestAnchors(parseHtml(page(`<p><a name="4">a</a></p><p><a name="4">b</a></p>`)).root);
    expect(result.anchors.map((a) => a.identifier)).toEqual(["4"]);
    expect(result.rejected).toHaveLength(1);
    expect(result.rejected[0]?.reason).toMatch(/already declared/u);
  });

  it("emits one marker, so the document names each place once", async () => {
    // `goya2` writes 28 anchors for 26 destinations, repeating `4` and `6`.
    const out = await md(page(`<p><a name="4">a</a></p><p><a name="4">b</a></p>`));
    expect(anchors(out)).toEqual(["::anchor{#4}"]);
    expect(out).toContain("a");
    expect(out).toContain("b");
  });
});

// ---------------------------------------------------------------------------
// Placement
// ---------------------------------------------------------------------------

describe("where the marker lands", () => {
  it("precedes the content it names", async () => {
    const out = await md(page(`<p>первый</p><p><a name="k">второй</a></p>`));
    const lines = out.split("\n").filter((l) => l.trim() !== "");
    const marker = lines.indexOf("::anchor{#k}");
    expect(marker).toBeGreaterThanOrEqual(0);
    expect(lines.slice(marker).join("\n")).toContain("второй");
    expect(lines.slice(0, marker).join("\n")).toContain("первый");
  });

  it("hoists out of an inline position rather than splitting the paragraph", async () => {
    const out = await md(page(`<p>начало <a name="k">середина</a> конец</p>`));
    const lines = out.split("\n").filter((l) => l.trim() !== "");
    expect(lines).toContain("::anchor{#k}");
    // One paragraph, still whole: the marker did not cut it in two.
    expect(out).toMatch(/начало середина конец/u);
  });

  it("never lands inside a construct that cannot hold a directive", async () => {
    // A table cell, a list item and a block quote all prefix or forbid a
    // directive line; the marker belongs before the construct.
    const out = await md(
      page(`<table><tr><th>Название</th><th>Год</th></tr><tr><td><a name="k">Альбом</a></td><td>1990</td></tr></table>`),
    );
    const lines = out.split("\n");
    const marker = lines.findIndex((l) => l === "::anchor{#k}");
    const firstRow = lines.findIndex((l) => l.includes("|"));
    expect(marker).toBeGreaterThanOrEqual(0);
    expect(firstRow).toBeGreaterThan(marker);
    expect(lines.every((l) => !/^[>\s]+::anchor/u.test(l))).toBe(true);
  });

  it("is emitted once even when the region is converted more than once", async () => {
    // Structure recovery is speculative: a region may be lowered, inspected and
    // thrown away. A claim taken by the losing attempt has to come back, or the
    // destination is attached to a block that never reaches the document.
    const out = await md(
      page(`<table><tr><td><p align="center"><b><a name="k">Альбом</a></b></p></td><td><img src="a.jpg" width="200" height="200"></td></tr></table>`),
    );
    expect(anchors(out)).toEqual(["::anchor{#k}"]);
  });

  it("keeps source order across many destinations", async () => {
    const body = [1, 2, 3, 4, 5].map((n) => `<p><a name="a${n}">Запись ${n}</a></p>`).join("");
    expect(anchors(await md(page(body)))).toEqual([
      "::anchor{#a1}",
      "::anchor{#a2}",
      "::anchor{#a3}",
      "::anchor{#a4}",
      "::anchor{#a5}",
    ]);
  });
});

// ---------------------------------------------------------------------------
// The passes that group blocks must not see a marker
// ---------------------------------------------------------------------------

describe("markers do not disturb the blocks around them", () => {
  it("leaves an image and its caption bound", async () => {
    // The defect this ordering exists for: with the marker inserted before the
    // grouping passes ran, `goya2` lost three `::: images` groups and six
    // captions, because an invisible line stood between each cover and the line
    // that names it.
    const withAnchor = await md(
      page(`<p align="center"><img src="cover.jpg" width="240" height="240" alt="Bahia Lady"></p><p align="center"><a name="k">Bahia Lady</a></p>`),
    );
    const withoutAnchor = await md(
      page(`<p align="center"><img src="cover.jpg" width="240" height="240" alt="Bahia Lady"></p><p align="center">Bahia Lady</p>`),
    );
    expect(withAnchor.replace(/^::anchor\{#k\}\n\n/mu, "")).toEqual(withoutAnchor);
  });

  it("changes nothing but the marker lines on a document that has one", async () => {
    const body = `<h1>Заголовок</h1><p>Первый абзац.</p><p><a name="k">Второй абзац.</a></p><p>Третий абзац.</p>`;
    const withAnchor = await md(page(body));
    const withoutAnchor = await md(page(body.replace(`<a name="k">`, "<span>").replace("</a>", "</span>")));
    // The marker line and the blank line that separates it from the block it
    // names; nothing else may differ.
    expect(withAnchor.replace(/^::anchor\{#[^}]*\}\n\n/gmu, "")).toEqual(withoutAnchor);
  });
});

// ---------------------------------------------------------------------------
// Mutation robustness
// ---------------------------------------------------------------------------

describe("mutation robustness", () => {
  const base = page(`<p class="t8"><a name="k" href="#other">Название</a></p>`);

  const mutations: Array<[string, string]> = [
    ["permuted attributes", page(`<p class="t8"><a href="#other" name="k">Название</a></p>`)],
    ["uppercase attribute name", page(`<p class="t8"><A HREF="#other" NAME="k">Название</A></p>`)],
    ["single-quoted values", page(`<p class="t8"><a name='k' href='#other'>Название</a></p>`)],
    ["renamed class", page(`<p class="zzz9"><a name="k" href="#other">Название</a></p>`)],
    [
      "extra transparent wrappers",
      page(`<p class="t8"><font color="#480048"><span><a name="k" href="#other">Название</a></span></font></p>`),
    ],
    ["id instead of name", page(`<p class="t8"><a id="k" href="#other">Название</a></p>`)],
  ];

  it.each(mutations)("%s produces the same document", async (_label, mutated) => {
    expect(await md(mutated)).toEqual(await md(base));
  });
});

// ---------------------------------------------------------------------------
// Accounting
// ---------------------------------------------------------------------------

describe("accounting", () => {
  it("a marker is not text, so it cannot inflate or deflate conservation", async () => {
    const result = await convertProbe(page(`<p><a name="k">Название альбома</a></p><p>Ещё текст.</p>`));
    expect(result.conservation.text.recall).toBe(1);
    expect(result.markdown).toContain("::anchor{#k}");
  });

  it("marks nothing when the region it named was removed upstream", async () => {
    // A one-pixel image is a counter, and normalization drops it and the empty
    // paragraph around it before structure recovery ever runs. The destination
    // goes with the content it named, and the ledger already says why the
    // content went — inventing a marker for it would send a reader to whatever
    // happened to follow.
    const result = await convertProbe(page(`<p><a name="k"><img src="spacer.gif" width="1" height="1"></a></p>`));
    expect(result.markdown).not.toContain("::anchor");
    expect(result.ledger.some((e) => e.terminal.kind === "REMOVED")).toBe(true);
  });

  it("gives a claim back, so a rolled-back attempt cannot keep a destination", () => {
    // The registry contract the speculative-emission snapshot rests on. Without
    // it the losing attempt claims every destination, the winning attempt finds
    // nothing left to claim, and the document silently carries no markers at
    // all — which is exactly what `barrios` did on the first run of this rule.
    const root = parseHtml(page(`<p><a name="k">x</a></p>`)).root;
    const registry = new AnchorRegistry(harvestAnchors(root));
    const paragraph = [...walkElements(root)].find((n) => n.tag === "p");
    expect(paragraph).toBeDefined();

    const before = registry.claims();
    expect(registry.claimIn(paragraph as LadomNode)).toEqual(["k"]);
    expect(registry.claimIn(paragraph as LadomNode)).toEqual([]); // claimed once only
    expect(registry.unclaimed()).toHaveLength(0);

    registry.restore(before);
    expect(registry.unclaimed().map((r) => r.identifier)).toEqual(["k"]);

    registry.claimIn(paragraph as LadomNode);
    registry.release(["k"]);
    expect(registry.unclaimed().map((r) => r.identifier)).toEqual(["k"]);
  });
});
